services:
  psql:
    container_name: postgres
    image: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./psql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - backend_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: dnadas98/priv:training_portal_backend
    env_file:
      - ./.env
    depends_on:
      - psql
    networks:
      - backend_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    networks:
      - backend_network
    ports:
      - "80:80"
      - "443:443"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# logging: ELK stack

#  elasticsearch:
#    image: elasticsearch:7.16.2
#    container_name: elasticsearch
#    restart: always
#    volumes:
#    - elastic_data:/usr/share/elasticsearch/data/
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m" # restrict mem usage
#      discovery.type: single-node
#    ports:
#    - '9200:9200'
#    - '9300:9300'
#    networks:
#      - elk

#  logstash:
#    image: logstash:7.16.2
#    container_name: logstash
#    restart: always
#    volumes:
#    - ./logstash/:/logstash_dir
#    command: logstash -f /logstash_dir/logstash.conf
#    depends_on:
#      - elasticsearch
#    ports:
#    - '9600:9600'
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m" # restrict mem usage
#    networks:
#      - elk

#  kibana:
#    image: kibana:7.16.2
#    container_name: kibana
#    restart: always
#    ports:
#    - '5601:5601'
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    networks:
#      - elk

networks:
#  elk:
  backend_network:
    driver: bridge

volumes:
#  elastic_data:
  db:

